name: Auto PR:release → main

on:
  push:
    branches:
      - release

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release

      - name: Create PR from release → main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: release
          destination_branch: main
          pr_title: "🔄 Auto PR: Sync release → main"
          pr_body: |
            This PR was automatically created by GitHub Actions when a commit was pushed to the `release` branch.
          pr_draft: false
