name: Auto PR from release to main

on:
  push:
    branches:
      - release

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release

      - name: Debug:Show current branch
        run: |
          echo "✅ Current Branch: $(git branch --show-current)"
          echo "✅ Git Remote:"
          git remote -v
          echo "✅ Last 5 commits:"
          git log --oneline -n 5
          echo "✅ Diff with main:"
          git fetch origin main
          git diff origin/main..HEAD

      - name: Create PR from release to main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: release
          destination_branch: main
          pr_title: "🔄 Auto PR: Sync release → main"
          pr_body: |
            This PR was automatically created by GitHub Actions on push to `release`.
          pr_draft: false
