name: Auto PR from release to main

on:
  push:
    branches:
      - release

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Create PR from release to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main        # Target branch
          head: release     # Source branch
          title: "🔄 Auto PR: Sync release → main"
          body: |
            This pull request was automatically created by GitHub Actions.
          draft: false
